xychart-beta
    title "Average Grid Query Latency"
    x-axis ["1K", "10K", "100K", "1M", "10M", "100M"]
    y-axis "Latency (ms)" 0 --> 17000
    line [2, 4, 18, 52, 868, 15898]
    line [22, 24, 26, 23, 52, 69]
