xychart-beta
    title "Storage by Dataset"
    x-axis ["1K", "10K", "100K", "1M", "10M", "100M"]
    y-axis "Size (MiB)" 0 --> 17000
    line [8, 12, 45, 171, 1627, 15976]
    line [0, 0, 3, 28, 353, 4035]
